name: Python application hello-angel:1.0.0

on:
  push:
    branches: [ "master" ]
  
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest

    - name: Ejecutar la aplicacion
      run: python app.py

    - name: Simular el deploy
      run: echo "Simulando el despliegue de la aplicacion"

    - name: Construir la imagen de docker
      run: docker build -t ghcr.io/ajvera2000/hello-angel:1.0.0 .

    - name: Login a GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Publicar la imagen
      run: docker push ghcr.io/Ajvera2000/hello-angel:1.0.0